spring:
  application:
    name: lab-server-1


  kafka:
#    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
#      group-id: my-group-id
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: my-group-id
#      bootstrap-servers: 127.0.0.1:9092
server:
  port: 8080
